image: python:3.13

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

cache:
  paths:
    - .pip-cache/
    - .venv/

stages:
  - lint
  - build
  - release
before_script:
  - python -V
  - pip install poetry
  - poetry config virtualenvs.in-project true
  - poetry install --no-root

lint:
  stage: lint
  script:
    - poetry run ruff check .
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

build:
  stage: build
  script:
    - poetry version $(git describe --tags --abbrev=0)
    - poetry build
  artifacts:
    paths:
      - dist/*.whl
      - dist/*.tar.gz
    expire_in: 1 week  # Default expiration for non-release builds
  rules:
    - if: $CI_COMMIT_TAG
      when: always
      variables:
        EXPIRE_IN: 'never'  # Set a longer expiration for release builds
    - when: never
