# Autogenerated by regenerate_enums.py. Do not edit.
from enum import Enum


class IntentName(Enum):
    TRACKBAGGAGE = "TrackBaggage"
    GREETING = "Greeting"
    AUTHENTICATE = "Authenticate"
    ANYTHINGELSE = "AnythingElse"
    BOOKFLIGHT = "BookFlight"
    GOODBYE = "Goodbye"
    FLIGHTDELAYUPDATE = "FlightDelayUpdate"
    FALLBACKINTENT = "FallbackIntent"
    CANCELFLIGHT = "CancelFlight"
    CHANGEFLIGHT = "ChangeFlight"
