# Autogenerated by regenerate_enums.py. Do not edit.
from enum import Enum


class TrackBaggageSlot(Enum):
    RESERVATIONNUMBER = "ReservationNumber"


class AuthenticateSlot(Enum):
    ACCOUNTID = "AccountId"


class BookFlightSlot(Enum):
    ORIGINCITY = "OriginCity"
    DEPARTUREDATE = "DepartureDate"
    ORIGIN_AIRPORT_CODE = "Origin_Airport_Code"
    RETURNDATE = "ReturnDate"
    DESTINATIONCITY = "DestinationCity"
    DESTINATION_AIRPORT_CODE = "Destination_Airport_Code"
    NUMBEROFPASSENGERS = "NumberOfPassengers"
    TRIPTYPE = "TripType"


class FlightDelayUpdateSlot(Enum):
    DEPARTUREAIRPORT = "DepartureAirport"
    FLIGHTNUMBER = "FlightNumber"


class CancelFlightSlot(Enum):
    RESERVATIONNUMBER = "ReservationNumber"


class ChangeFlightSlot(Enum):
    NEWDEPARTUREDATE = "NewDepartureDate"
    RESERVATIONNUMBER = "ReservationNumber"


LexSlot = TrackBaggageSlot | AuthenticateSlot | BookFlightSlot | FlightDelayUpdateSlot | CancelFlightSlot | ChangeFlightSlot

LexSlot_Classes = {
    "TrackBaggageSlot": TrackBaggageSlot,
    "AuthenticateSlot": AuthenticateSlot,
    "BookFlightSlot": BookFlightSlot,
    "FlightDelayUpdateSlot": FlightDelayUpdateSlot,
    "CancelFlightSlot": CancelFlightSlot,
    "ChangeFlightSlot": ChangeFlightSlot,
}
